openapi: 3.0.1
info:
  title: dev-apim-func-01
  description: Import from "dev-apim-func-01" Function App
  version: '1.0'
servers:
  - url: https://dev-apim-100.azure-api.net/dev-apim-func-01
paths:
  /api-trigger:
    post:
      summary: api-trigger
      operationId: post-api-trigger
      responses:
        '200':
          description: ''
    get:
      summary: api-trigger
      operationId: get-api-trigger
      responses:
        '200':
          description: ''
components:
  securitySchemes:
    apiKeyHeader:
      type: apiKey
      name: Ocp-Apim-Subscription-Key
      in: header
    apiKeyQuery:
      type: apiKey
      name: subscription-key
      in: query
security:
  - apiKeyHeader: [ ]
  - apiKeyQuery: [ ]