apiNames:
  - dev-apim-func-01

backendNames:
  - dev-apim-func-01

diagnosticNames: []

loggerNames: []

namedValueNames:
  - dev-apim-func-01-key   # The named value containing the API key

productNames: []

subscriptionNames: []

tagNames: []

policyFragmentNames: []
