openapi: 3.0.1
info:
  title: Movies API
  description: ''
  version: '1.0'
servers:
  - url: https://apim-test-vm.azure-api.net/moviesget
paths:
  /moviesget:
    get:
      summary: Get_Movies_Details_By_Id
      operationId: get-movies-details-by-id
      responses:
        '200':
          description: ''
  /moviespost:
    post:
      summary: Add_Movie_Detail
      operationId: add-movie-detail
      responses:
        '200':
          description: ''
components:
  securitySchemes:
    apiKeyHeader:
      type: apiKey
      name: Ocp-Apim-Subscription-Key
      in: header
    apiKeyQuery:
      type: apiKey
      name: subscription-key
      in: query
security:
  - apiKeyHeader: [ ]
  - apiKeyQuery: [ ]