openapi: 3.0.1
info:
  title: Mock Response
  description: ''
  version: ''
servers:
  - url: https://apim-test-vm.azure-api.net
paths:
  /mock-response:
    get:
      summary: Mock_Response
      operationId: mock-response
      parameters:
        - name: id
          in: query
          required: true
          schema:
            type: ''
      responses:
        '200':
          description: ''
          content:
            application/json:
              example:
                status: success
                owner: John Key
components:
  securitySchemes:
    apiKeyHeader:
      type: apiKey
      name: Ocp-Apim-Subscription-Key
      in: header
    apiKeyQuery:
      type: apiKey
      name: subscription-key
      in: query
security:
  - apiKeyHeader: [ ]
  - apiKeyQuery: [ ]