openapi: 3.0.1
info:
  title: Weather API
  description: ''
  version: '1.0'
servers:
  - url: https://apim-test-vm.azure-api.net/weather
paths:
  /weather:
    get:
      summary: weather_info
      operationId: weather-info
      parameters:
        - name: city
          in: query
          required: true
          schema:
            type: ''
      responses:
        '200':
          description: ''
components:
  securitySchemes:
    apiKeyHeader:
      type: apiKey
      name: Ocp-Apim-Subscription-Key
      in: header
    apiKeyQuery:
      type: apiKey
      name: subscription-key
      in: query
security:
  - apiKeyHeader: [ ]
  - apiKeyQuery: [ ]